### ISSUE TITLE
Search in new version not working

### ISSUE THREAD

**Issue by feophan** [unicode-table/symbl-data#162]
Starting from today search of glyphs by name returns empty list.

E.g. 'i macron' query in the old site returns

![image](https://user-images.githubusercontent.com/31542979/220167096-1c2c1479-f560-4273-842d-6cb87261710c.png)

and in the new site:

![image](https://user-images.githubusercontent.com/31542979/220167206-6fa020ae-3dcb-4659-a688-a45a3d135301.png)

**Comment by asanov** [comment]
Fixed.
